#!/bin/bash

PORT=""
ORIGIN=""
NAME=""
USER=""
IDENTITY=""
CDN="cs5700cdnproject.ccs.neu.edu"

while getopts "p:o:n:u:i:" opt; do
  case $opt in
    p)
      PORT=$OPTARG
      ;;
    o)
      ORIGIN=$OPTARG
      ;;
    n)
      NAME=$OPTARG
      ;;
    u)
      USER=$OPTARG
      ;;
    i)
      IDENTITY=$OPTARG
      ;;
    \?)
      echo "INVALID ARGUMENT"
      exit 1
      ;;
  esac
done
# ========== HTTP SERVERS ==========
# scp ec2-hosts to cwd
scp -i $IDENTITY $USER@$CDN:/course/cs5700sp17/ec2-hosts.txt .

# Parse ec2-hosts.txt and run each server
for line in $(tail -n +3 < ec2-hosts.txt | cut -f1)
do
  split=($line)
  echo $line
  bash runSingleHttp.sh -u $USER -i $IDENTITY -p $PORT -o $ORIGIN -d "${split[0]}"
done

# ========== DNS SERVER ============
echo "DNS"
ssh $USER@$CDN -n -i $IDENTITY -o StrictHostKeyChecking=no "cd gilpin-project5 && exec -a DNS_SERVER ./dnsserver -p $PORT -n $NAME &> /dev/null 2>&1 &" &&

# remove ec2-hosts.txt
rm ec2-hosts.txt
